name: Build and publish docker image 

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [build-publish]

jobs:
  build-publish:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Set version
        uses: dotnet/nbgv@v0.4
        id: nbgv
        with:
          setAllVars: false
          
      - name: Build and Publish as versioned
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: ositemindex.aggregator # Provide only Docker image name, tag will be automatically set to latest
          image-tag: ${{ steps.nbgv.outputs.SimpleVersion }}

      - name: Build and Publish as latest
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: ositemindex.aggregator # Provide only Docker image name, tag will be automatically set to latest
